import { SanityLive } from "@/sanity/lib/live";
import type { Metadata } from "next";
import { Header } from "@/components/Header";

// import "./../globals.css";

export const metadata: Metadata = {
    title: "Layer Caker",
    description: "Generated by create next app",
};

export default function FrontendLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header />
            {children}
            <SanityLive />
        </>
    );
}
